# Generated by Django 4.1.4 on 2023-01-07 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0005_profile_years_of_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='BussinessUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('jury', models.ManyToManyField(to='account.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('BU', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='idea.bussinessunit')),
            ],
        ),
    ]
