# Generated by Django 4.1.4 on 2023-01-07 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_profile_years_of_experience'),
        ('idea', '0002_rename_bussinessunit_businessunit'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdeaImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='idea_images')),
            ],
        ),
        migrations.AddField(
            model_name='idea',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='idea',
            name='ideator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.profile'),
        ),
        migrations.AddField(
            model_name='idea',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='businessunit',
            name='jury',
            field=models.ManyToManyField(blank=True, null=True, to='account.profile'),
        ),
        migrations.AddField(
            model_name='idea',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, to='idea.ideaimage'),
        ),
    ]
