# Generated by Django 4.1.4 on 2023-01-07 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('idea', '0003_ideaimage_idea_body_idea_ideator_idea_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='ideator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
