# Generated by Django 4.1.4 on 2023-01-07 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_profile_years_of_experience'),
        ('idea', '0004_alter_idea_ideator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessunit',
            name='jury',
            field=models.ManyToManyField(blank=True, to='account.profile'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='images',
            field=models.ManyToManyField(blank=True, to='idea.ideaimage'),
        ),
    ]
