# Generated by Django 4.1.4 on 2023-01-07 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0005_alter_businessunit_jury_alter_idea_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idea',
            old_name='body',
            new_name='description',
        ),
        migrations.AddField(
            model_name='idea',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
