# Generated by Django 4.1.4 on 2023-01-07 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0006_rename_body_idea_description_idea_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='name',
        ),
        migrations.AddField(
            model_name='idea',
            name='heading',
            field=models.TextField(blank=True, null=True),
        ),
    ]
