# Generated by Django 4.1.4 on 2023-01-07 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0007_remove_idea_name_idea_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
