# Generated by Django 4.1.4 on 2023-01-07 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0008_idea_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='heading',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
