# Generated by Django 4.1.4 on 2023-01-08 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0009_alter_idea_heading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessunit',
            name='jury',
        ),
    ]
