# Generated by Django 4.1.4 on 2023-01-08 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0010_remove_businessunit_jury'),
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='BU',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='program.businessunit'),
        ),
        migrations.DeleteModel(
            name='BusinessUnit',
        ),
    ]
