# Generated by Django 4.1.4 on 2023-01-08 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0012_rename_bu_idea_business_unit_remove_idea_heading_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='ideator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='idea.ideator'),
        ),
    ]
