# Generated by Django 4.1.4 on 2023-01-08 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
        ('idea', '0013_alter_idea_ideator'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='program.program'),
        ),
    ]
