# Generated by Django 4.1.4 on 2023-01-08 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0015_alter_idea_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='idea',
            name='is_on_hold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='idea',
            name='is_pending',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='idea',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
