# Generated by Django 4.1.4 on 2023-01-08 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('idea', '0016_idea_is_accepted_idea_is_on_hold_idea_is_pending_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IdeaImage',
        ),
        migrations.AlterField(
            model_name='idea',
            name='ideator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Ideator',
        ),
    ]
