# Generated by Django 4.1.4 on 2023-01-09 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0018_alter_idea_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Active'), (2, 'Handoff'), (3, 'Completed'), (4, 'Paused'), (5, 'Stopped'), (6, 'Rejected')], default=0),
        ),
    ]
