# Generated by Django 4.1.4 on 2023-01-09 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0019_alter_idea_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='is_accepted',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='is_on_hold',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='is_pending',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='is_rejected',
        ),
        migrations.AlterField(
            model_name='idea',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Active'), (2, 'Handoff'), (3, 'Completed'), (4, 'Paused'), (5, 'Stopped'), (6, 'Put On Hold'), (7, 'Rejected')], default=0),
        ),
    ]
