# Generated by Django 4.1.4 on 2023-01-09 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0020_remove_idea_is_accepted_remove_idea_is_on_hold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='actual_net_revenue',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='idea',
            name='projected_revenue',
            field=models.BigIntegerField(null=True),
        ),
    ]
