# Generated by Django 4.1.4 on 2023-01-09 07:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0021_idea_actual_net_revenue_idea_projected_revenue'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='idea',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
