# Generated by Django 4.1.4 on 2023-01-09 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0022_idea_created_idea_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='idea',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
