# Generated by Django 4.1.4 on 2023-01-09 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0023_alter_idea_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
