# Generated by Django 4.1.4 on 2023-01-07 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_profile_department_profile_field_of_work_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='years_of_experience',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
