# Generated by Django 4.1.4 on 2023-01-08 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0002_alter_businessunit_jury'),
        ('account', '0007_profile_jury_programs'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='jury_business_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='program.businessunit'),
        ),
    ]
