# Generated by Django 4.1.4 on 2023-01-09 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('program', '0002_alter_businessunit_jury'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessunit',
            name='jury',
        ),
        migrations.AddField(
            model_name='businessunit',
            name='jury',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
