# Generated by Django 4.1.4 on 2023-01-09 07:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0004_program_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessunit',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businessunit',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='program',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
