# Generated by Django 4.1.4 on 2023-01-09 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0005_businessunit_created_businessunit_updated_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
