# Generated by Django 4.1.4 on 2023-01-09 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0006_alter_program_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessunit',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
